Testing mismatch between src and dist

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,8 +9,7 @@ on:
         types: [assigned, opened, synchronize, reopened]
 
 jobs:
-    # Dynamically calculate the version of this build
-    version:
+    prep:
         runs-on: ubuntu-latest
         permissions:
             contents: read
@@ -38,12 +37,12 @@ jobs:
     # A regular project build. Test results will explicitly be reported during a pull request build
     build:
         runs-on: ubuntu-latest
-        needs: version
-        if: ${{ needs.version.outputs.abort != 'true' }}
+        needs: prep
+        if: ${{ needs.prep.outputs.abort != 'true' }}
         permissions:
             contents: read
         env:
-            MRMAT_VERSION: ${{ needs.version.outputs.version }}
+            MRMAT_VERSION: ${{ needs.prep.outputs.version }}
         steps:
             - name: Checkout out our code
               uses: actions/checkout@v5.0.0
@@ -56,8 +55,21 @@ jobs:
               run: npm ci
             - name: Apply version
               run:
-                  npm version ${{ needs.version.outputs.version }}
+                  npm version ${{ needs.prep.outputs.version }}
                   --no-git-tag-version
+            - name: Verify dist/ results match with src/
+              if: ${{ github.event_name == 'pull_request' && github.target_ref == 'refs/heads/main' }}
+              run: |
+                npm run bundle
+                if [ ! -d dist/ ]; then
+                  echo "dist/ directory not found"
+                  exit 1
+                fi
+                if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
+                  echo "Detected uncommitted changes. GH Actions need to be built and committed outside CI:"
+                  git diff --ignore-space-at-eol --text dist/
+                  exit 1
+                fi
             - name: Lint
               run: npm run ci-lint
             - name: Test
@@ -68,13 +80,12 @@ jobs:
     # The release job only executes when pushing to the main branch
     release:
         if:
-            ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'
-            }}
+            ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
         runs-on: ubuntu-latest
         permissions:
             contents: write
         needs:
-            - version
+            - prep
             - build
         steps:
             - name: Create Release
@@ -83,9 +94,9 @@ jobs:
               env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               with:
-                  tag_name: ${{ needs.version.outputs.version }}
-                  release_name: Release ${{ needs.version.outputs.version }}
+                  tag_name: ${{ needs.prep.outputs.version }}
+                  release_name: Release ${{ needs.prep.outputs.version }}
                   body: |
-                      Release ${{ needs.version.outputs.version }}
+                      Release ${{ needs.prep.outputs.version }}
                   draft: false
                   prerelease: false
